#!/bin/bash
#
# CSCS Eiger One-Time Setup Script
#
# Sets up the build environment with Intel MKL for HiPO benchmarks.
# Run this ONCE before submitting benchmark jobs.
#
# Usage:
#   ./setup_cscs.sh
#
# Prerequisites:
#   uenv repo create
#   uenv image pull prgenv-gnu/25.11:v1
#
# Reference: https://docs.cscs.ch/build-install/uenv/

readonly UENV_IMAGE="prgenv-gnu/25.11:v1"
readonly UENV_ARCH="zen2"  # Eiger uses AMD EPYC Rome (zen2)
readonly MKL_ENV_NAME="hipo-mkl"

# Verify SCRATCH is set (required on CSCS)
if [[ -z "${SCRATCH:-}" ]]; then
  echo "ERROR: SCRATCH not set. Run this on CSCS systems." >&2
  exit 1
fi

readonly MKL_ENV_DIR="${SCRATCH}/${MKL_ENV_NAME}"
readonly UENV_SPACK_DIR="${SCRATCH}/uenv-spack"
readonly ACTIVATE_SCRIPT="${MKL_ENV_DIR}/view/activate.sh"

echo "=========================================="
echo "CSCS HiPO Setup Script"
echo "=========================================="
echo "MKL environment: ${MKL_ENV_DIR}"
echo ""

# Check if already set up
if [[ -f "${ACTIVATE_SCRIPT}" ]]; then
  echo "MKL environment already exists."
  echo "To rebuild: rm -rf ${MKL_ENV_DIR}"
  exit 0
fi

# Step 1: Set up architecture-aware paths
# CSCS clusters use different architectures (x86 on Eiger, ARM on Santis).
# This pattern allows same home directory across clusters.
# Reference: https://docs.cscs.ch/guides/terminal/#managing-x86-and-arm
echo "Step 1: Setting up architecture-aware paths"
echo "=========================================="

xdgbase="${HOME}/.local/$(uname -m)"
export XDG_DATA_HOME="${xdgbase}/share"
export XDG_CONFIG_HOME="${xdgbase}/config"
export XDG_STATE_HOME="${xdgbase}/state"
export PATH="${xdgbase}/bin:${PATH}"

arch=$(uname -m)
echo "Architecture: ${arch}"
echo "XDG base: ${xdgbase}"

# Step 2: Install uv (required by uenv-spack)
# Reference: https://docs.astral.sh/uv/getting-started/installation/
echo ""
echo "Step 2: Checking uv installation"
echo "=========================================="

if command -v uv > /dev/null 2>&1; then
  uv_version=$(uv --version)
  echo "uv already installed: ${uv_version}"
else
  echo "Installing uv to ${xdgbase}..."
  mkdir -p "${xdgbase}/bin"
  export UV_INSTALL_DIR="${xdgbase}"

  uv_installer="${SCRATCH}/uv-install.sh"
  curl -L https://astral.sh/uv/install.sh -o "${uv_installer}"
  sh "${uv_installer}"
  rm "${uv_installer}"

  # Source the env file to add uv to PATH
  # shellcheck source=/dev/null  # Auto-generated by uv installer
  source "${xdgbase}/env"
fi

# Step 3: Clone uenv-spack
echo ""
echo "Step 3: Setting up uenv-spack"
echo "=========================================="

if [[ ! -d "${UENV_SPACK_DIR}" ]]; then
  git clone https://github.com/eth-cscs/uenv-spack.git "${UENV_SPACK_DIR}"
else
  echo "uenv-spack already exists at ${UENV_SPACK_DIR}"
fi

export PATH="${UENV_SPACK_DIR}:${PATH}"

# Step 4: Create MKL build environment
echo ""
echo "Step 4: Creating MKL build environment"
echo "=========================================="

uenv run "${UENV_IMAGE}" --view=spack -- "${UENV_SPACK_DIR}/uenv-spack" "${MKL_ENV_DIR}" --uarch="${UENV_ARCH}" --name="${MKL_ENV_NAME}"

# Step 5: Add MKL spec to the generated spack.yaml
# The uenv-spack template creates a spack.yaml with view configuration.
# We add our package to the specs list, preserving all other settings.
echo ""
echo "Step 5: Adding intel-oneapi-mkl to environment"
echo "=========================================="

spack_yaml="${MKL_ENV_DIR}/env/spack.yaml"

# Packages to install:
#   cmake@3.22: - HiGHS requires cmake 3.22+ (Eiger has 3.20)
#   eigen - Required by HiPO solver
#   intel-oneapi-mkl - Required for Pardiso solver
# Specs with version ranges must be quoted to prevent YAML parsing issues
# Reference: https://spack.readthedocs.io/en/latest/packages_yaml.html
cmake_spec="'cmake@3.22:'"
eigen_spec="'eigen@3.4'"  # Pin to 3.4.x (5.0.0 has build issues)
mkl_spec="intel-oneapi-mkl"

# Patterns for detecting spack.yaml format from uenv-spack template:
#   Placeholder:   "- # add specs here"
#   Empty array:   "specs: []"
template_specs_placeholder="- # add specs here"
empty_specs_array="specs: \[\]"

# Replacement spec entries (2-space indent to match uenv-spack format)
# Use \n to add multiple specs on separate lines
specs_entries="- ${cmake_spec}\n  - ${eigen_spec}\n  - ${mkl_spec}"

# Show current specs section for debugging
echo "Current spack.yaml specs section:"
grep -A 5 "specs" "${spack_yaml}" || echo "  (specs section not found)"

# Check if specs are already in the file
# Use --fixed-strings for literal matching (patterns contain # and spaces)
# Use -- to mark end of options (patterns start with -)
# Reference: https://www.gnu.org/software/grep/manual/grep.html
if grep --quiet --fixed-strings -- "${mkl_spec}" "${spack_yaml}"; then
  echo "Specs already present"
elif grep --quiet --fixed-strings -- "${template_specs_placeholder}" "${spack_yaml}"; then
  # uenv-spack template: replace placeholder comment with our specs
  sed -i "s/${template_specs_placeholder}/${specs_entries}/" "${spack_yaml}"
  echo "Added cmake, eigen, and intel-oneapi-mkl"
elif grep --quiet --fixed-strings -- "${empty_specs_array}" "${spack_yaml}"; then
  # Empty array format: replace with multi-line list
  sed -i "s/${empty_specs_array}/specs:\n  ${specs_entries}/" "${spack_yaml}"
  echo "Added cmake, eigen, and intel-oneapi-mkl"
else
  echo "ERROR: Unknown spack.yaml format. Please add specs manually." >&2
  exit 1
fi

# Show updated specs section for verification
echo ""
echo "Updated spack.yaml specs section:"
grep -A 5 "specs" "${spack_yaml}"

# Step 6: Build the environment
echo ""
echo "Step 6: Building (this may take a while)"
echo "=========================================="

uenv run "${UENV_IMAGE}" --view=spack -- "${MKL_ENV_DIR}/build"

echo ""
echo "=========================================="
echo "Setup Complete"
echo "=========================================="
echo "Activate with: source ${ACTIVATE_SCRIPT}"
